### ISSUE TITLE
QR code is taking long to open

### ISSUE THREAD

**Issue by innyanzi** [rosskhanas/react-qr-code#100]
I have put a QRCode component in the React native modal, but it takes 10 seconds to open.

**Comment by tharaniya1992** [comment]
I also have a same problem. Does anyone have a solution for this?

**Comment by nyzszn** [comment]
@tharaniya1992 I recommend you switch to one of these "react-native-qrcode": "^0.2.7",
    "react-native-qrcode-svg": "^5.2.0",
Packages.

**Comment by tharaniya1992** [comment]
> @tharaniya1992 I recommend you switch to one of these "react-native-qrcode": "^0.2.7",
> "react-native-qrcode-svg": "^5.2.0",
> Packages.

thank you

**Comment by rosskhanas** [comment]
I tried to reproduce the issue and I see no issues with rendering, I tried https://github.com/rosskhanas/react-qr-code/tree/master/storybooks/native. If there is still an issue, please provide a link to repo and I will look at that.
