### ISSUE TITLE
ART has been removed from Expo

### ISSUE THREAD

**Issue by silvestreh** [rosskhanas/react-qr-code#122]
As of SDK 36, `ART` has been removed from Expo. Would be sweet to update this lib so it works without `ART`, though to be completely honest, I do not know what that entails.

**Comment by rosskhanas** [comment]
One of the options could be to make this package work with `react-native-svg`. For example, use an alternative import, something like: `react-qr-code/svg`...

**Comment by yfunk** [comment]
@rosskhanas Since `@react-native-community/art` isn't actively maintained and seems close to being deprecated it might be a good idea to migrate to `react-native-svg` altogether.

Let me know what you think, I can definitely help out by creating a PR.

**Comment by rosskhanas** [comment]
@yfunk I guess that is a good idea, we can make v2 based on `react-native-svg` instead of art. What do you think?

Would appreciate your help with the PR 🙂

**Comment by yfunk** [comment]
> I guess that is a good idea, we can make v2 based on `react-native-svg` instead of art. What do you think?

Sounds good, I'll have a look at it towards the weekend and open a PR, we can discuss further details there 🙂
