### ISSUE TITLE
[Feature Request] Canvas / img tag output

### ISSUE THREAD

**Issue by wyqydsyq** [rosskhanas/react-qr-code#125]
It would be nice if the returned VDOM could be the SVG data embedded into either a canvas or `img`, allowing it to be more easily saved as a PNG using native browser interactions

**Comment by IanVS** [comment]
Just as a small datapoint, I chose to use this package over others because it did _not_ use canvas or have a lot of extra capabilities.  It's the smallest and simplest package I could find to generate an SVG QR code.

**Comment by jelizarovas** [comment]
> Just as a small datapoint, I chose to use this package over others because it did _not_ use canvas or have a lot of extra capabilities. It's the smallest and simplest package I could find to generate an SVG QR code.

Do you have a way to export your SVG?

**Comment by IanVS** [comment]
>Do you have a way to export your SVG?

What do you mean by export it?  I show it on a website for a 2fa code.
