### ISSUE TITLE
Using without React Native yeilds unmet dependency

### ISSUE THREAD

**Issue by Spark3000** [rosskhanas/react-qr-code#132]
![Screenshot 2020-11-01 at 15 21 18](https://user-images.githubusercontent.com/4939629/97804068-319bee80-1c56-11eb-8dae-31dac268c036.png)

**Comment by rosskhanas** [comment]
@Spark3000 `@react-native-community/art` package yields that, not this package. I guess you can create an issue in https://github.com/react-native-art/art repo.

**Comment by Spark3000** [comment]
Ah yes. Sorry. Will do. Thanks.
