### ISSUE TITLE
Download generated QR code

### ISSUE THREAD

**Issue by jonasdev** [rosskhanas/react-qr-code#135]
Any idea how to download the QR Code on click?

**Comment by Creativogee** [comment]
Does not currently have this feature. Had to use the html2canvas package to grab the container.

**Comment by jonasdev** [comment]
const svg = document.getElementById("qrcode");
    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    const img = new Image();
    img.onload = function () {
      canvas.width = img.width;
      canvas.height = img.height;
      ctx.drawImage(img, 0, 0);
      const pngFile = canvas.toDataURL("image/png");

      const downloadLink = document.createElement("a");
      downloadLink.download = "qrcode";
      downloadLink.href = `${pngFile}`;
      downloadLink.click();
    };

    img.src = "data:image/svg+xml;base64," + btoa(svgData);

    };
    
    Solved it like this. Wrapping the SVG with an anchor. Called the function above with a click event I assigned to a download button

**Comment by rosskhanas** [comment]
Here is a demo how to do it: https://rosskhanas.github.io/react-qr-code/

**Comment by hrqmonteiro** [comment]
> Here is a demo how to do it: https://rosskhanas.github.io/react-qr-code/

This is not a Demo, you didn't teached how to make the button to download, wtf.

**Comment by iway1** [comment]
would be cool to have a better API for this and have it built in, the JS required to do it shouldn't be viewed by humans - 

this would be really nice:

```ts
<QRCode 
  renderDownloadButton={({download})=><button onClick={download}>download</button>}
/>
```

**Comment by kevin-dev71** [comment]
the generated QR file cannot be scanned... anybody have this problem or just me?
