### ISSUE TITLE
Next.js Integration

### ISSUE THREAD

**Issue by eokwukwe** [rosskhanas/react-qr-code#142]
Please how can this package be used in a **Next.js** application?

**Comment by domhede** [comment]
What problem are you having?  I just imported into a component within a Next app no worries.

**Comment by eokwukwe** [comment]
> What problem are you having? I just imported into a component within a Next app no worries.

@domhede I have started to use it yet. I just wanted to know if there is anything to do differently when using it with `Next.js` since it is SSR.

**Comment by rosskhanas** [comment]
> > What problem are you having? I just imported into a component within a Next app no worries.
> 
> @domhede I have not started to use it yet. I just wanted to know if there is anything to do differently when using it with `Next.js` since it is SSR.

Should be no problems rendering on a server-side.
