### ISSUE TITLE
Incomplete Type definitons for the QRCode component.

### ISSUE THREAD

**Issue by trm217** [rosskhanas/react-qr-code#154]
I am using the  QRCode component in a typescript project and I have noticed, that the type definitions for the components properties is incomplete. As seen in the JSX code of the component you pass down all properties, so basically all properties that the default HTML elements have can also be given to the QRCode component. However the type definition is far more limited and that for f.e. the id prop can't be given to the component without typescript linting it as an error.

**Comment by rosskhanas** [comment]
@trm217 can this issue be closed?

**Comment by trm217** [comment]
The problem it's self is solved by my pr. However I wonder if the JS prop-types declaration might ha e to be extended too?
Also the docs could be updated to mention that all other arguments are passed to the SVG element. If you think this would be a good idea, I'm willing to create a second pr later today that adds this 👍🏻

**Comment by rosskhanas** [comment]
@trm217 I guess there is no need to change prop types, I think it is just fine.

If you are willing to create another PR with improved docs, I will be happy to marge it for sure! 😃
