### ISSUE TITLE
Suggestion: move prop-types to devDependencies

### ISSUE THREAD

**Issue by IanVS** [rosskhanas/react-qr-code#161]
For projects using typescript or flow, `prop-types` isn't necessary and only adds additional size to the bundle.  Right now it makes up 5.9% of the bundle size of this project (https://bundlephobia.com/package/react-qr-code@2.0.1).  Is it possible to only include it as a dev dependency and exclude it from the production bundle?

**Comment by rosskhanas** [comment]
@IanVS it's been a long time since I used typescript, but isn't there something like https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types?

**Comment by IanVS** [comment]
I'm not using babel, but perhaps rollup has something similar.  Also, I see that prop-types [recommends](https://github.com/facebook/prop-types#how-to-depend-on-this-package) that libraries have `prop-types` in `dependencies`.
