### ISSUE TITLE
npm 7 fails to install if missing react-native-svg

### ISSUE THREAD

**Issue by IanVS** [rosskhanas/react-qr-code#162]
Since react-native-svg is listed as a peer dependency, npm 7 will fail to install this package unless `--legacy-peer-deps` or `--force` is used.  I might suggest removing it as a peer dependency, since it's fine to use this package without it, right?

**Comment by rosskhanas** [comment]
@IanVS `react-native-svg` is required to have this package work on React Native.

**Comment by IanVS** [comment]
I'm sorry, I left out some important context.  I'm not using react-native.  I think that having the instructions in the docs as you do is probably sufficient, and I'm not sure there's a benefit to including it as a peer dependency, especially since you're not specifying a particular version of the package that this one requires.  I've seen a fair bit of confusing from users in other repos about peer-deps that won't install with npm 7, so I thought I'd bring it up here as a way to potentially reduce friction.

**Comment by draperunner** [comment]
I think you could use `peerDependenciesMeta` to tag `react-native-svg` as an _optional_ peer dependency:

```diff
 "peerDependencies": {
   "react-native-svg": "*"
 },
+"peerDependenciesMeta": {
+  "react-native-svg": {
+     "optional": true
+  }
+}
```

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

**Comment by KaniZ0r** [comment]
Can we have this updated? Currently react-native-svg peerDependency installs react@18 and it causes a lot of issues since then there is multiple react versions installed.
