### ISSUE TITLE
[Feature Request] Allow specifying a title for the SVG

### ISSUE THREAD

**Issue by IanVS** [rosskhanas/react-qr-code#166]
For accessibility, it's suggested to add a `<Title>` [element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) as the first child of an SVG.  It would be great if there was a prop to allow specifying this text.

**Comment by rosskhanas** [comment]
https://github.com/rosskhanas/react-qr-code/commit/f863963064d6f75068cb68ae7a5e4e3e6e0d61f5
