### ISSUE TITLE
2.0.2 was not built before publish

### ISSUE THREAD

**Issue by MartijnHols** [rosskhanas/react-qr-code#172]
I was trying to make my QRCode scale based on CSS values and ran into issues with the `style` prop being set. Upon inspecting the source in this repository, I could not figure out why until I found commit 985b7ec2fd0a6d4799d852022b7c727d917742a6, where the style props were removed (which is what I need). That same day you released 2.0.2;

![image](https://user-images.githubusercontent.com/4565223/141757535-e8956224-6f4c-4a85-9650-dd9f5f3ac89a.png)

However when I look at the compiled code that's available under 2.0.2, I still see the previous version leading to my conclusion that the library wasn't built prior to publishing. Can you do a fresh publish to make these changes available please?

**Comment by rosskhanas** [comment]
@MartijnHols plz check `v2.0.3`.
