### ISSUE TITLE
QR not working when Android device activate Darkmode 

### ISSUE THREAD

**Issue by idindrakusuma** [rosskhanas/react-qr-code#178]
Hi @rosskhanas
Thank you for your hard work in making this awesome package. I'm already used this package for more than 6 months now.
But, I have some reports from my users about this QR. This QR Not work as usual when user activates dark mode in several android devices. 

I'm already changed the `fgColor`, try to revert the other color but still same.  You can see the result like image below:
![photo_2021-12-19 08 26 30](https://user-images.githubusercontent.com/10141928/146660364-4f59535e-c577-4c01-adfd-37eb603deddd.jpeg)

**Comment by idindrakusuma** [comment]
I'm use this device:
- Xiaomi Redmi Note 8
- Google Chrome

**Comment by lukesdm** [comment]
How are you activating dark mode @idindrakusuma ?
I think this issue is caused by Chrome's dark mode implementation, which is still behind an experimental flag. It seems that if you don't have a dark mode style-sheet, it uses a custom shader. Does it still happen in the latest version of chrome? If so, it would be worth looking at the Chromium bug tracker and maybe reporting it there.

**Comment by Neffes1987** [comment]
<img width="386" alt="Screenshot 2022-05-20 at 09 59 15" src="https://user-images.githubusercontent.com/20636819/169471579-6ceaf6c1-5f56-4953-a9b0-9c134763c004.png">
@idindrakusuma I have faced the same problem, and find out that it can be solver by the adding additional setting "bgColor". The most interesting thing that it does not work with black color, but works with others

<img width="1408" alt="Screenshot 2022-05-20 at 10 01 54" src="https://user-images.githubusercontent.com/20636819/169472013-06f8a611-9340-4cb8-83bd-b3ed20975b88.png">
<img width="1371" alt="Screenshot 2022-05-20 at 10 02 32" src="https://user-images.githubusercontent.com/20636819/169472024-9463d70f-fb3d-4227-bbd0-8ea65f184f46.png">

**Comment by rosskhanas** [comment]
Looks like not a bug on this lib? Can be closed?
