### ISSUE TITLE
(Feature request) New parameter to add a margin

### ISSUE THREAD

**Issue by fappaz** [rosskhanas/react-qr-code#180]
As mentioned [here](https://www.qrcode.com/en/howto/code.html), [here](https://qrd.by/blog/2014/07/15/minimum-size-qr-code/) and [here](https://www.qreveal.com/blog/qr-code-margins/), it's recommended for QR codes to have a margin (a.k.a. quiet zone) of at least 4 units.

This component draws an SVG with 0 margin for the QR code, which is not a big deal when simply displaying it in HTML, given that you can add the margin with CSS.

However, the browser also allows you to save the SVG locally (right click > Save image as), resulting in a PNG with no margin at all. This becomes a UX issue when people try to reuse the image they just downloaded, and some scanners struggle to read it without the margin.

My suggestion is to support a new parameter like below:

```
<QrCode value="foobar" marginSize={32} />
```

For backwards compatibility, `marginSize` should be 0px by default, and it could reuse the colour provided in `bgColor` as well.

What are your thoughts?

**Comment by wall3n** [comment]
I think you can just customize it with for example Styled comonents or just css

**Comment by rosskhanas** [comment]
I agree with @wall3n. I would like to keep this package minimal.

@fappaz you can just add a `style` attribute like this:

```
<QrCode value="foobar" style={{ padding: 32, backgroundColor: 'same as bgColor' }} />
```

**Comment by wall3n** [comment]
Yeah I think this type of components should be without style, just functional. For anyone who wants to add style react I think offers a buch of ways to add it

**Comment by fappaz** [comment]
Sorry I think I didn't make myself clear. 

Applying CSS to the component is only adding a margin to the HTML element while it's being rendered on the browser, but not to the SVG drawing per se. 

Just try your own code above. There is indeed a padding when displaying the QR code on the DOM, but once you right-click and download it as a PNG, there's no margin. As I mentioned in the original post, I've had users trying to scan this QR code they downloaded and failing to do so because there's no margin.

Therefore what I'm suggesting is an option to draw a thick border around the SVG so the QR code can have that quite zone once downloaded.  Unless there's another way I'm not aware of.

**Comment by rosskhanas** [comment]
@fappaz did you try smth like this https://stackoverflow.com/a/27546213/1308757?

**Comment by fappaz** [comment]
Nevermind, I just noticed that the project I was working on had multiple QR code packages installed, and the imported component (coincidentally also called `QRCode`) was from a different lib.

I set up another project from scratch and installed just this lib, that's when I realised I can't even right-click on and download it because it's an SVG instead of a canvas. Even if I embedded a child SVG as you suggested, it wouldn't solve the issue because I couldn't download it anyway - unless maybe I plot it into a canvas first with JS, but then the component starts becoming less practical.

Perhaps the lib could have a new param to render the QR code as canvas instead of SVG, allowing users to download it as an image. Then my request would make sense again.

Anyway, thanks for your help.

**Comment by lukesdm** [comment]
Hey, sorry to bug you again about this. I think you should consider re-opening this - the quiet-zone is an important part of the QR code and I would suggest putting it in by default. You can see the effects in the screenshots from the readme -  the QR on the phone on the left doesn't scan, due to the black bezel. 
![image](https://user-images.githubusercontent.com/2824165/158571914-99a8acac-02de-454d-9da3-b9f7e6c001e0.png)

If you agree that's it worth doing, I can put in a PR.

**Comment by rosskhanas** [comment]
@lukesdm you can wrap a qr code component into a white view. Is there any problem with that?

**Comment by lukesdm** [comment]
> @lukesdm you can wrap a qr code component into a white view. Is there any problem with that?

I think a few of us have run into issues now, around dark mode, or when the QR code touches a dark object. Adding the white spacing around it is a fine work-around but I think it would save a lot of collective head-scratching in the long-run, as dark mode is getting more popular. Maybe just a note in the readme would be ok?

**Comment by rosskhanas** [comment]
@lukesdm sure, I would be grad to receive a PR 🙂
