### ISSUE TITLE
How can I let the QR code resize to fill its container?

### ISSUE THREAD

**Issue by KalvinWei** [rosskhanas/react-qr-code#188]
It seems the size value makes the QR code fixed to certain pixels. How can I let it automatically resize to fill its container?
Cheers.

**Comment by rosskhanas** [comment]
It is not possible, you need to pass a `size` value.

**Comment by SaadBazaz** [comment]
Just for people having the same issue...

@rosskhanas has made an example of responsive QR. 
https://github.com/rosskhanas/react-qr-code/blob/master/demo/src/components/App.js

I've used it, works good.

**Comment by trippingcats** [comment]
The link is dead, @SaadBazaz do you still have the demo somewehere? Thanks.

**Comment by rosskhanas** [comment]
@trippingcats https://github.com/rosskhanas/react-qr-code/blob/master/demo/src/Demo.js
