### ISSUE TITLE
Support CSS vars

### ISSUE THREAD

**Issue by jsamr** [rosskhanas/react-qr-code#193]
This will not work in version 2.0.5:

```jsx
    <QRCode
      size="var(--qr-size)"
      bgColor="var(--qr-bg-color)"
      fgColor="var(--qr-fg-color)"
      value={url}
    />
```

**Comment by rosskhanas** [comment]
@jsamr size needs to be a number because there are math operations done in code. However, `bgColor` and `fgColor` can be CSS variables.

**Comment by rosskhanas** [comment]
@jsamr you hardcode render any QR code size and scale it with CSS. Here is an example: https://github.com/rosskhanas/react-qr-code/pull/204#issuecomment-1134552612

So CSS variables can be used without any problem 😃
