### ISSUE TITLE
Add viewbox attribute

### ISSUE THREAD

**Issue by duesenfranz** [rosskhanas/react-qr-code#194]
Setting a viewbox attribute would make it easy to have a responsive QR code which scales with the container element.

**Comment by rosskhanas** [comment]
@duesenfranz great suggestion, I don't mind receiving a PR 🙂

**Comment by rosskhanas** [comment]
ViewBox attributed is supported the same as any other `svg` tag attributes. Here is a commit with a code and a demo: https://github.com/rosskhanas/react-qr-code/commit/1f43adb3b41305b9a3ab004b337b3bd34bf9fe6c
