### ISSUE TITLE
Installation error | React version 18.1.0

### ISSUE THREAD

**Issue by pramudnadula** [rosskhanas/react-qr-code#203]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-qr-reader@3.0.0-beta-1
npm ERR! node_modules/react-qr-reader
npm ERR!   react-qr-reader@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\PramudNadula\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PramudNadula\AppData\Local\npm-cache\_logs\2022-05-08T08_09_11_187Z-debug.log

**Comment by rosskhanas** [comment]
@pramudnadula your error is related to some `react-qr-reader` package, not this.
