### ISSUE TITLE
Changelog and Releases

### ISSUE THREAD

**Issue by dzienisz** [rosskhanas/react-qr-code#216]
Hi Ross,

amazing job with the library! I use it and love it!

Have you thought about adding proper change-log file or use GitHub releases feature?

I strongly recommend using https://github.com/conventional-changelog/standard-version as this is in my opinion industry standard.

I think that would facilitate this library as more reliable and would help check what really changed without checking all commits.

I know this is additional feature and would take some time, if I would find some time and you would not do it already I would try to code this feature.

Thanks again
Kamil (Poland, Warsaw)

**Comment by dzienisz** [comment]
It looks good 🤟

W dniu pt., 30.09.2022 o 20:22 Ross Khanas ***@***.***>
napisał(a):

**Comment by rosskhanas** [comment]
@IanVS can you please share your QR codes that look worse? I'm curious, because codes quality was actually improved.

**Comment by IanVS** [comment]
After digging in a bit more, I agree, the codes look better. I think they are just being snapshotted by chromatic differently now that there are just a couple of paths vs many individual squares. It looked blurry in the snapshots, but fine in the browser. 

My point with my previous comment though was that it wound nice to have a changelog to look through to identify what changes betw versions. I was able to find the relevant PR from the list of commits though.

**Comment by rosskhanas** [comment]
@IanVS sorry, I will try to do the changelog properly.
