### ISSUE TITLE
Not showing while Printing the page on Firefox

### ISSUE THREAD

**Issue by amjed-ali-k** [rosskhanas/react-qr-code#222]
Documentation URL:-
https://rosskhanas.github.io/react-qr-code/

When Ctrl + P  [Firefox]
Firefox 107.0 (64-bit) - Ubuntu 22.04
![image](https://user-images.githubusercontent.com/86785660/204152079-b622d0e3-9259-4bb6-b84d-d40047727b4c.png)

When Ctrl + P [Google Chrome / Brave Browser]
Brave [Version 1.45.131 Chromium: 107.0.5304.110 (Official Build) (64-bit)] - Ubuntu 22.04
![image](https://user-images.githubusercontent.com/86785660/204152115-c9eafff7-a499-462a-a7ad-a1349c9d9e4c.png)

**Comment by jkarttunen** [comment]
Firefox printing does work on myown code on localhost, just not on the documentation URl, even with the same value.

**Comment by che-wavefin** [comment]
If you save the file, the QR code will show on the actual file. It's just not showing on the print preview. 
<img width="1311" alt="Screen Shot 2023-05-24 at 6 21 32 PM" src="https://github.com/rosskhanas/react-qr-code/assets/112013423/f77dbac9-7408-4e4c-8ac7-1710bc168a3d">

**Comment by amjed-ali-k** [comment]
Issue still persists

**Comment by amjed-ali-k** [comment]
> Firefox printing does work on my own code on localhost, just not on the documentation URL, even with the same value. Firefox 112.0 / Mac

This issue still exists on one of my project. I had to look for other qrcode libs in that case.

**Comment by Destinyyyy** [comment]
adding the css attribute on the @print attribute seems to do the trick:
"print-color-adjust: exact;"
