### ISSUE TITLE
JS event 

### ISSUE THREAD

**Issue by samducker** [rosskhanas/react-qr-code#223]
Hey does this emit a JS event when scanned for data analytics/tracking purposes?

I tried running monitorEvents(window) and nothing is firing so I wondered if this is actually possible or if the only way was to do this on the url side? e.g. a special link for my website's QR code.

**Comment by EdoElgx** [comment]
I've not reviewed the code, but I can't conceive a way to detect it's been scanned. 

You could set up a short URL like in https://www.shorturl.at/ that redirects to your target URL. This type of services typically provide you with at least a counter.

**Comment by mercpls** [comment]
Just use a unique url param. You'll know who scanned it, assuming it's owning an in app when you capture the url param in the app.

**Comment by rosskhanas** [comment]
It seems like the issue is out of the scope of this lib.
