### ISSUE TITLE
White space border on Google Chrome

### ISSUE THREAD

**Issue by suryanto23** [rosskhanas/react-qr-code#226]
Hi, 
Thank you for your work and effort on this amazing library.

I tried to generate a QR in Google Chrome (Ver 107.0.5304.122) with your library. However, it has a white space border on the rendered QR image.
I tested with another browser which is Firefox and it works fine without this issue.

Could you please take a look and assist me? or in case it was a browser issue?
Thank you in advance.

![test](https://user-images.githubusercontent.com/67571269/205882584-d10dd303-9d5a-4b18-b596-bc0b65ad6527.png)

**Comment by rosskhanas** [comment]
https://github.com/rosskhanas/react-qr-code/pull/218
