### ISSUE TITLE
`QRCodeProps.size?` is typed as `number` but this doesn't allow to use `auto`

### ISSUE THREAD

**Issue by evroon** [rosskhanas/react-qr-code#246]
I would like to pass `auto` as `size`, but `size` is typed as `number`. If I try `auto`, it just works so shouldn't `auto` also be allowed?

https://github.com/rosskhanas/react-qr-code/blob/8adcd9ce7b564b2daab082aee7700f7fb8a6a02d/types/index.d.ts#L6

it's passed here from what I understand to `width` and `height`, so it should just work:

https://github.com/rosskhanas/react-qr-code/blob/8adcd9ce7b564b2daab082aee7700f7fb8a6a02d/src/QRCodeSvg/index.js#L21

```tsx
src/components/dashboard/layout.tsx:23:13 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: QRCodeProps | Readonly<QRCodeProps>): QRCode', gave the following error.
    Type 'string' is not assignable to type 'number'.
  Overload 2 of 2, '(props: QRCodeProps, context: any): QRCode', gave the following error.
    Type 'string' is not assignable to type 'number'.

23             size='auto'
```

So I guess it should be typed as `number | 'auto'`?

**Comment by rosskhanas** [comment]
@evroon It may work on the web, but unfortunately not with react-native https://github.com/software-mansion/react-native-svg/issues/1429

**Comment by evroon** [comment]
Ahh okay haha that sounds like quite a shortcoming, but then I will just ignore the error in my own code.
Thanks for the response.
