### ISSUE TITLE
Download QR Code.

### ISSUE THREAD

**Issue by prafuldivani** [rosskhanas/react-qr-code#249]

**Comment by rosskhanas** [comment]
https://github.com/rosskhanas/react-qr-code/issues/187

**Comment by prafuldivani** [comment]
Hi @rosskhanas, I would like to add a download feature to this repository. Should I proceed with that?

**Comment by rosskhanas** [comment]
@prafuldivani it is already possible, please check the demo: https://rosskhanas.github.io/react-qr-code/ :)

**Comment by christianhelp** [comment]
For anyone who is also looking for the  the **actual** source code for the demo: https://github.com/rosskhanas/react-qr-code/blob/master/demo/src/Demo.js
