### ISSUE TITLE
Allow 100% and percentage to be passed for width

### ISSUE THREAD

**Issue by kyeshmz** [rosskhanas/react-qr-code#252]
Hi, this is a suggestion to add 100% or width percentage for the size prop, as it is allowed for svgs, and can be passed currently, but has type errors. 

I can make a PR if this seems ok.

**Comment by drjvtlkr** [comment]
It already has 100% width by default

**Comment by rosskhanas** [comment]
Please see the [demo](https://rosskhanas.github.io/react-qr-code/) how to achieve 100% width percentage.
