### ISSUE TITLE
react-native dependency

### ISSUE THREAD

**Issue by khelkun** [rosskhanas/react-qr-code#260]
It seems it tries to install react-native and react-native-svg when running `npm i react-qr-code` or `npm i --no-optional react-qr-code`

**Comment by detaybey** [comment]
thanks for breaking our build. 

ERR! Found: react@18.3.1
npm ERR! node_modules/react
npm ERR!   react@"18.x" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0 || ^18.0.0" from @storybook/addon-essentials@7.6.19
npm ERR!   node_modules/@storybook/addon-essentials
npm ERR!     dev @storybook/addon-essentials@"^7.3.0" from the root project
npm ERR!   10 more (react-dom, @storybook/addon-links, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! react-qr-code@"2.0.13" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.2.0" from react-native@0.74.1
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"*" from react-native-svg@15.3.0
npm ERR!     node_modules/react-native-svg
npm ERR!       peerOptional react-native-svg@"*" from react-qr-code@2.0.13
npm ERR!       node_modules/react-qr-code
npm ERR!         react-qr-code@"2.0.13" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
