### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by chengivan2** [rosskhanas/react-qr-code#262]
I just spun up a new NextJs project and react-qr-code is the first dependency am installing manually. I have tried installing three times and have gotten the same error on each try. I am not using TypeScript in my project. All pre-installed dependencies are on their latest version. The screenshot displays the error I am refering to.
![react-qr-code-error](https://github.com/rosskhanas/react-qr-code/assets/96454861/af21dc3c-ccb8-43d4-96e8-887e46e31ed4)

**Comment by kevtechi** [comment]
Same issue, seems to be a peer dep issue with the react version

**Comment by chengivan2** [comment]
Which version of React works for you? Did you try switching to any particular version and got it to work?

**Comment by alizadeh-m** [comment]
I think the react version needs to be updated to at least 18.3 to fix _this_ issue 🤔

**Comment by rosskhanas** [comment]
What react version do you guys use? This package does not require any specific version of react...

**Comment by chengivan2** [comment]
I am using the latest major version: ^18. I also didn't think that the difference between the minor versions mattered that much, unless that needs to be checked.

**Comment by kevtechi** [comment]
Try spinning up a new NextJS project: `npx create-next-app@latest` 

Then try installing this package. It fails at the installation step with the above error.

**Comment by NewYanko** [comment]
> What react version do you guys use? This package does not require any specific version of react...

weirdly, having react 18 in deps breaks the installation, but updating to v18.3.1, react-qr-code installs just fine

**Comment by chengivan2** [comment]
@alizadeh-m I'm afraid you are right.

> I think the react version needs to be updated to at least 18.3 to fix _this_ issue 🤔

I just tested your theory and it works.

@rosskhanas I think that comment could help.

**Comment by rosskhanas** [comment]
I just removed that peer dependency. Tbh, I have no idea why npm decided to install optional peer deps. But I think everyone's life is better if there is no react-native-svg peer dep lol
