### ISSUE TITLE
Wrong generation for QRCode

### ISSUE THREAD

**Issue by LLSean** [rosskhanas/react-qr-code#263]
I used this code to generate qrcode, but the result is wrong. How to resolve this problem?
<QRCode value={111)} bgColor="#000000" fgColor="#FFFFFF" />
<img width="262" alt="image" src="https://github.com/rosskhanas/react-qr-code/assets/1560188/d0ac0338-d32f-49a8-8309-f288a49e0bdf">

**Comment by rosskhanas** [comment]
https://github.com/rosskhanas/react-qr-code?tab=readme-ov-file#api
