### ISSUE TITLE
Time limiter

### ISSUE THREAD

**Issue by edubaldin13** [rosskhanas/react-qr-code#264]
Hey there, I'm using this lib to generate QR CODE for a payment method called PIX here in brazil, this issue is to give an insight about time limit, for example if a generate a qr code with an expiration timer of 30 minuts after that it wont be able to access the link

By now I'm at work and can't take a look about it, but when I get home I'll try to, best regards buddies 👯‍♂️

**Comment by rosskhanas** [comment]
It is out of the scope of this library.
