### ISSUE TITLE
Black square instead of a qrcode on android

### ISSUE THREAD

**Issue by rsmelo92** [rosskhanas/react-qr-code#80]
Showing a black square instead of a qrcode on Android
![image](https://user-images.githubusercontent.com/16295402/57974191-d9522d80-798a-11e9-83e3-ebb47faafdaa.png)

Only works when toggle inspector...
![image](https://user-images.githubusercontent.com/16295402/57974198-e66f1c80-798a-11e9-9daf-886c77ab9cf0.png)

**Comment by rosskhanas** [comment]
@rsmelo92 it seems like there is a big in React Native repo which will be fixed in the next release https://github.com/facebook/react-native/issues/17565#issuecomment-490914899.
