### ISSUE TITLE
QR code generating not working well

### ISSUE THREAD

**Issue by StefanBurscher** [rosskhanas/react-qr-code#82]
This one does not work because of the colors (in the documentation is said CSS colors and this is a CSS color): 
```
<QRCode
              value={"hey"}
              size={141}
              bgColor='black'
              fgColor='white'
            />
```

This one works:
```
<QRCode
              value={"hey"}
              size={141}
              bgColor='#FFF'
              fgColor='#000'
            />
```
Please change fix this bug... I lost about 4 hours figuring out what caused the problem generating broken QR...

**Comment by rosskhanas** [comment]
Fixed `README.md`.
